### ISSUE TITLE
moby-derp always thinks containers are out of date

### ISSUE THREAD

**Issue by Supermathie** [mpalmer/moby-derp#2]
On my server, moby-derp always thinks the non-root containers are out of date.

Here's an example of two successive runs:

```
michael@andor:~/moby-derp$ MOBY_DERP_LOG_LEVEL=debug bundle exec moby-derp prometheus.yml 
Reading configuration file /etc/moby-derp.conf
Reading configuration file prometheus.yml
@name: "prometheus"
@containers: {"auth-proxy"=>{"image"=>"discourse/auth-proxy:20200609.185704", "environment"=>{"ORIGIN_URL"=>"http://localhost:9090", "SSO_SECRET"=>"swordfish", "SSO_URL"=>"https://discourse.example.net", "PROXY_URL"=>"http://prometheus.example.net", "LISTEN_URL"=>"[::]:6580"}}, "server"=>{"image"=>"prom/prometheus:latest", "command"=>["--config.file=/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus/data-v3", "--storage.tsdb.retention.time=90d", "--web.console.libraries=/prometheus/console/libraries/", "--web.console.templates=/prometheus/console/templates", "--web.enable-lifecycle", "--web.external-url=http://prometheus.example.net"], "mounts"=>[{"source"=>"server", "target"=>"/prometheus"}]}}
Hostname is andor
@common_environment: {}
@common_labels: {}
@root_labels: {}
@common_mounts: []
@expose: []
@publish: []
Checking root container
Calculated container name is prometheus (@root_container: true, @config.name: prometheus.root, @pod.name: prometheus
Config hash for existing container prometheus is "sha256:c255a2d9e0e61bbcdf4fbc1adea4974b59236ffaf169caf283ad96cf3932f6c0"
New config hash is "sha256:c255a2d9e0e61bbcdf4fbc1adea4974b59236ffaf169caf283ad96cf3932f6c0"
Container prometheus is up-to-date
Root container ID is e134881b3e3b495bebe281980cc0a4367aa3f341f9bb97b7d451692bfffa15dd
Removing stale container prometheus.server
Removing stale container prometheus.auth-proxy
Checking container prometheus.auth-proxy
Calculated container name is prometheus.auth-proxy (@root_container: false, @config.name: prometheus.auth-proxy, @pod.name: prometheus
Container prometheus.auth-proxy does not exist; creating it
Checking container prometheus.server
Calculated container name is prometheus.server (@root_container: false, @config.name: prometheus.server, @pod.name: prometheus
Container prometheus.server does not exist; creating it
```

```
michael@andor:~/moby-derp$ MOBY_DERP_LOG_LEVEL=debug bundle exec moby-derp prometheus.yml 
Reading configuration file /etc/moby-derp.conf
Reading configuration file prometheus.yml
@name: "prometheus"
@containers: {"auth-proxy"=>{"image"=>"discourse/auth-proxy:20200609.185704", "environment"=>{"ORIGIN_URL"=>"http://localhost:9090", "SSO_SECRET"=>"swordfish", "SSO_URL"=>"https://discourse.example.net", "PROXY_URL"=>"http://prometheus.example.net", "LISTEN_URL"=>"[::]:6580"}}, "server"=>{"image"=>"prom/prometheus:latest", "command"=>["--config.file=/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus/data-v3", "--storage.tsdb.retention.time=90d", "--web.console.libraries=/prometheus/console/libraries/", "--web.console.templates=/prometheus/console/templates", "--web.enable-lifecycle", "--web.external-url=http://prometheus.example.net"], "mounts"=>[{"source"=>"server", "target"=>"/prometheus"}]}}
Hostname is andor
@common_environment: {}
@common_labels: {}
@root_labels: {}
@common_mounts: []
@expose: []
@publish: []
Checking root container
Calculated container name is prometheus (@root_container: true, @config.name: prometheus.root, @pod.name: prometheus
Config hash for existing container prometheus is "sha256:c255a2d9e0e61bbcdf4fbc1adea4974b59236ffaf169caf283ad96cf3932f6c0"
New config hash is "sha256:c255a2d9e0e61bbcdf4fbc1adea4974b59236ffaf169caf283ad96cf3932f6c0"
Container prometheus is up-to-date
Root container ID is e134881b3e3b495bebe281980cc0a4367aa3f341f9bb97b7d451692bfffa15dd
Removing stale container prometheus.server
Removing stale container prometheus.auth-proxy
Checking container prometheus.auth-proxy
Calculated container name is prometheus.auth-proxy (@root_container: false, @config.name: prometheus.auth-proxy, @pod.name: prometheus
Container prometheus.auth-proxy does not exist; creating it
Checking container prometheus.server
Calculated container name is prometheus.server (@root_container: false, @config.name: prometheus.server, @pod.name: prometheus
Container prometheus.server does not exist; creating it
```

My prometheus.yml:
```
containers:
  auth-proxy:
    image: discourse/auth-proxy:20200609.185704
    environment:
      ORIGIN_URL: http://localhost:9090
      SSO_SECRET: swordfish
      SSO_URL: https://discourse.example.net
      PROXY_URL: http://prometheus.example.net
      LISTEN_URL: "[::]:6580"

  server:
    image: prom/prometheus:latest
    command:
    - '--config.file=/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus/data-v3'
    - '--storage.tsdb.retention.time=90d'
    - '--web.console.libraries=/prometheus/console/libraries/'
    - '--web.console.templates=/prometheus/console/templates'
    - '--web.enable-lifecycle'
    - '--web.external-url=http://prometheus.example.net'
    mounts:
      - source: server
        target: /prometheus
```

docker version:
```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Tue, 03 Sep 2019 19:59:35 +0200
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Tue Sep  3 17:59:35 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

docker info:
```
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 18.09.1
Storage Driver: zfs
 Zpool: storage
 Zpool Health: ONLINE
 Parent Dataset: storage/srv
 Space Used By Parent: 2886224
 Space Available: 657011083520
 Parent Quota: no
 Compression: lz4
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 1.0.0~rc6+dfsg1-3
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.0-9-amd64
Operating System: Debian GNU/Linux 10 (buster)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.84GiB
Name: andor
ID: RKRO:5RYX:TJHO:NIX4:FCID:4MOI:MSQI:BNJP:J632:OC47:7DXO:TQ26
Docker Root Dir: /storage/srv/docker-data
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
